"use client";

import { useMemo, useState, type CSSProperties } from "react";

type Dimension = "Coachability" | "Confidence" | "Communication" | "Leadership" | "Competitiveness" | "Emotional Control" | "Resilience" | "Focus" | "Learning Style" | "Growth Mindset" | "Decision Making" | "Adaptability" | "Teamwork" | "Self-Awareness" | "Motivation" | "Discipline" | "Accountability" | "Pressure Response" | "Curiosity" | "Independence";
type Answers = Record<number, number>;
type Choice = { text: string; evidence: Partial<Record<Dimension, number>> };
type Question = { text: string; context: string; choices: Choice[] };
type PlayerGender = "boy" | "girl";
type ArchetypeMatch = { name:string; keys:Dimension[]; avatar:number; description:string; match:number };
type ArchetypeVoice = { role:string; leadership:string; pressure:string; mistakes:string; focus:string; parent:string[] };
type DevelopmentPlan = { why:string; action:string; progress:string };

const dimensions: Dimension[] = ["Coachability","Confidence","Communication","Leadership","Competitiveness","Emotional Control","Resilience","Focus","Learning Style","Growth Mindset","Decision Making","Adaptability","Teamwork","Self-Awareness","Motivation","Discipline","Accountability","Pressure Response","Curiosity","Independence"];
const reportDimensions: Dimension[] = ["Coachability","Confidence","Leadership","Communication","Resilience","Growth Mindset","Competitiveness","Focus","Decision Making","Teamwork"];
const questions: Question[] = [
  {text:"A coach stops an activity and gives you a correction you did not expect. What are you most likely to do?",context:"During training",choices:[
    {text:"Try the correction immediately and judge it after a few repetitions.",evidence:{Coachability:88,Adaptability:78,Curiosity:62}},
    {text:"Ask one question so I understand exactly what the coach wants first.",evidence:{Curiosity:92,Communication:78,Coachability:75}},
    {text:"Listen, but keep using what has normally worked for me until I see the difference.",evidence:{Independence:82,Confidence:72,Adaptability:38}},
    {text:"Think about the correction quietly and work on it later when I have more space.",evidence:{"Self-Awareness":75,Independence:72,Communication:42}}
  ]},
  {text:"You receive the ball in a crowded area and have very little time. What usually happens?",context:"Fast decision",choices:[
    {text:"I play the first safe option I notice.",evidence:{"Decision Making":70,Teamwork:72,Confidence:58}},
    {text:"I protect the ball for a moment and look for more information.",evidence:{Focus:80,"Decision Making":76,"Pressure Response":68}},
    {text:"I attempt the aggressive option if it could break a line.",evidence:{Confidence:84,Competitiveness:76,"Decision Making":63}},
    {text:"I often decide only after the pressure has already arrived.",evidence:{"Pressure Response":38,"Decision Making":34,Focus:45}}
  ]},
  {text:"A teammate makes the same mistake twice and it affects your side of the field. What do you do?",context:"Team communication",choices:[
    {text:"Give a short, specific instruction during the next stoppage.",evidence:{Communication:88,Leadership:82,Teamwork:76}},
    {text:"Adjust my own position to cover the problem without saying much.",evidence:{Adaptability:84,Teamwork:72,Communication:45}},
    {text:"Encourage the teammate first so the message does not lower confidence.",evidence:{Teamwork:90,Leadership:72,"Emotional Control":75}},
    {text:"Wait for the coach to address it because that is the coach’s role.",evidence:{Discipline:66,Independence:38,Leadership:35}}
  ]},
  {text:"Your team concedes after a mistake you were involved in. What is your next response?",context:"Mistake recovery",choices:[
    {text:"Quickly identify my part, then focus on the restart.",evidence:{Accountability:90,Resilience:88,"Emotional Control":84}},
    {text:"Try to make up for it immediately with a big play.",evidence:{Competitiveness:90,Resilience:68,"Decision Making":48}},
    {text:"Replay the mistake in my mind so I do not repeat it.",evidence:{"Self-Awareness":78,Focus:52,Resilience:40}},
    {text:"Look first at what the team shape or another player could have done differently.",evidence:{"Decision Making":64,Accountability:32,Teamwork:46}}
  ]},
  {text:"The session includes a repetitive technical exercise you already know. How do you approach it?",context:"Training habits",choices:[
    {text:"Set a personal accuracy or speed target to keep it demanding.",evidence:{Motivation:90,Discipline:86,Competitiveness:78}},
    {text:"Focus closely on one small technical detail each repetition.",evidence:{Focus:92,Discipline:82,"Growth Mindset":78}},
    {text:"Complete it correctly, but save most of my energy for game-like work.",evidence:{"Decision Making":70,Independence:72,Motivation:55}},
    {text:"My attention usually drops unless the coach adds competition.",evidence:{Competitiveness:78,Focus:35,Discipline:42}}
  ]},
  {text:"You are moved to an unfamiliar position just before kickoff. What feels most natural?",context:"Role change",choices:[
    {text:"Ask for the two most important responsibilities, then play.",evidence:{Adaptability:90,Communication:82,Coachability:82}},
    {text:"Use what I know about soccer and work the role out as the game develops.",evidence:{Independence:90,Confidence:80,Adaptability:72}},
    {text:"Play cautiously until I understand what is happening around me.",evidence:{Focus:75,"Decision Making":64,Confidence:44}},
    {text:"It takes me a while to stop thinking about my usual position.",evidence:{Adaptability:35,Resilience:48,"Emotional Control":52}}
  ]},
  {text:"Your team is losing late, but you have been playing well personally. What drives your decisions?",context:"Competitive moment",choices:[
    {text:"Increase the risk in my play because the team needs a change.",evidence:{Competitiveness:92,Confidence:82,"Decision Making":62}},
    {text:"Keep doing my role and trust the team structure.",evidence:{Discipline:88,Teamwork:82,"Emotional Control":80}},
    {text:"Try to get the ball more often and take responsibility.",evidence:{Leadership:84,Confidence:84,Independence:75}},
    {text:"Focus on finishing strongly so my own level does not drop.",evidence:{Motivation:78,Discipline:72,Teamwork:48}}
  ]},
  {text:"A coach explains a new tactical pattern. Which first step helps you most?",context:"Learning preference",choices:[
    {text:"Watch the coach or teammates demonstrate the movement.",evidence:{"Learning Style":90,Focus:72,Coachability:70}},
    {text:"Hear the reason behind the pattern and the problem it solves.",evidence:{Curiosity:90,"Decision Making":78,"Learning Style":72}},
    {text:"Walk through my own part slowly before adding pressure.",evidence:{"Learning Style":84,Discipline:72,Independence:68}},
    {text:"Start playing and learn from what goes wrong in live action.",evidence:{Adaptability:84,Confidence:74,"Growth Mindset":76}}
  ]},
  {text:"You disagree with a referee’s important decision. What are you most likely to do?",context:"Emotional control",choices:[
    {text:"Say something briefly, then move into position for the next play.",evidence:{Communication:68,"Emotional Control":78,Resilience:80}},
    {text:"Say nothing and use the frustration as extra energy.",evidence:{Competitiveness:84,"Emotional Control":76,Communication:45}},
    {text:"Ask the referee calmly what was seen when there is a chance.",evidence:{Communication:86,"Emotional Control":84,Curiosity:68}},
    {text:"The decision stays with me and affects how I play for a while.",evidence:{"Emotional Control":32,Resilience:35,Focus:38}}
  ]},
  {text:"You notice a teammate is quiet and struggling during a difficult game. What do you do?",context:"Team awareness",choices:[
    {text:"Check in with the teammate and offer one useful cue.",evidence:{Leadership:90,Communication:88,Teamwork:88}},
    {text:"Give visible encouragement but keep my own focus on the game.",evidence:{Teamwork:78,Focus:82,Leadership:64}},
    {text:"Take on more responsibility so the teammate has less pressure.",evidence:{Leadership:82,Competitiveness:72,Teamwork:68}},
    {text:"Leave space; some players recover better without attention.",evidence:{"Self-Awareness":64,Independence:68,Communication:42}}
  ]},
  {text:"After a match, the coach asks what you thought of your performance. What comes first?",context:"Reflection",choices:[
    {text:"One thing I helped the team with and one thing I need to improve.",evidence:{"Self-Awareness":92,Accountability:86,"Growth Mindset":82}},
    {text:"The moments that changed the result of the game.",evidence:{"Decision Making":82,Competitiveness:75,"Self-Awareness":70}},
    {text:"I ask what the coach noticed before giving my own view.",evidence:{Coachability:86,Curiosity:78,"Self-Awareness":62}},
    {text:"I need time or video before I can give a useful answer.",evidence:{Focus:76,"Self-Awareness":70,Communication:48}}
  ]},
  {text:"You are practicing alone and no one will know how hard you worked. What keeps the session going?",context:"Internal motivation",choices:[
    {text:"A clear plan or number of repetitions I decided beforehand.",evidence:{Discipline:92,Independence:88,Motivation:80}},
    {text:"The feeling that I am getting sharper as I work.",evidence:{Motivation:90,"Growth Mindset":84,Curiosity:62}},
    {text:"Imagining a future game or opponent where the work will matter.",evidence:{Competitiveness:88,Motivation:84,Focus:70}},
    {text:"I usually train better when someone else provides structure or energy.",evidence:{Teamwork:68,Independence:32,Motivation:48}}
  ]},
  {text:"Your first plan with the ball is no longer available. What do you tend to do?",context:"Adaptability",choices:[
    {text:"Move the ball to a teammate and immediately reposition.",evidence:{Teamwork:86,Adaptability:84,"Decision Making":80}},
    {text:"Protect it and wait for a new option to appear.",evidence:{Confidence:78,Focus:82,"Decision Making":75}},
    {text:"Use skill or speed to create a new option myself.",evidence:{Independence:88,Confidence:84,Competitiveness:72}},
    {text:"Return to the safest available option, even if it goes backward.",evidence:{Discipline:76,"Decision Making":78,"Pressure Response":72}}
  ]},
  {text:"A teammate gives you feedback that conflicts with what you thought happened. What do you do?",context:"Receiving feedback",choices:[
    {text:"Ask what the teammate saw and compare it with my view.",evidence:{Coachability:88,Communication:88,Curiosity:84}},
    {text:"Acknowledge it, then decide privately whether it fits.",evidence:{Independence:82,"Self-Awareness":74,"Emotional Control":72}},
    {text:"Explain what I saw so we can agree on the next action.",evidence:{Communication:86,Confidence:78,Teamwork:76}},
    {text:"Prefer to wait for the coach’s opinion before changing anything.",evidence:{Coachability:66,Independence:40,Discipline:68}}
  ]},
  {text:"You are chosen to lead a warm-up for the first time. How do you handle it?",context:"Leadership",choices:[
    {text:"Give clear directions and keep the group moving.",evidence:{Leadership:90,Communication:88,Confidence:84}},
    {text:"Use the normal team routine so everyone already knows what to do.",evidence:{Discipline:86,Teamwork:82,Leadership:68}},
    {text:"Ask another player to help demonstrate while I organize.",evidence:{Teamwork:90,Leadership:78,Communication:80}},
    {text:"Keep it simple because being watched makes me less comfortable.",evidence:{Accountability:72,Confidence:38,"Pressure Response":42}}
  ]},
  {text:"The coach gives the team a difficult goal that may take weeks to reach. What is your first reaction?",context:"Growth mindset",choices:[
    {text:"Break it into smaller targets I can measure each week.",evidence:{"Growth Mindset":90,Discipline:88,Focus:84}},
    {text:"Want to understand why this goal matters for our team.",evidence:{Curiosity:90,Teamwork:76,Motivation:76}},
    {text:"Feel motivated by proving we can do something difficult.",evidence:{Competitiveness:90,Confidence:78,Motivation:84}},
    {text:"Wait to see whether the plan works before fully buying into it.",evidence:{"Decision Making":68,Independence:70,Coachability:42}}
  ]},
  {text:"A high-pressure penalty shootout is approaching. Which response sounds most like you?",context:"Pressure",choices:[
    {text:"I want to take one and decide my routine early.",evidence:{"Pressure Response":92,Confidence:90,Discipline:76}},
    {text:"I will take one if selected, but I do not need to volunteer.",evidence:{Accountability:82,"Emotional Control":78,Teamwork:70}},
    {text:"I focus on supporting teammates and staying ready for what follows.",evidence:{Teamwork:88,Focus:82,"Pressure Response":68}},
    {text:"I can perform, but my thoughts and body feel noticeably different.",evidence:{"Self-Awareness":84,"Pressure Response":48,"Emotional Control":50}}
  ]},
  {text:"You see a teammate trying a creative play that has already failed twice. What is your instinct?",context:"Risk and creativity",choices:[
    {text:"Encourage the idea but suggest a better moment to try it.",evidence:{Communication:88,"Decision Making":86,Teamwork:84}},
    {text:"Keep making supporting runs because the play may work next time.",evidence:{Teamwork:88,Resilience:80,"Growth Mindset":76}},
    {text:"Ask for a simpler option until the team regains control.",evidence:{Leadership:78,Discipline:84,"Decision Making":80}},
    {text:"Let the teammate decide; I prefer to focus on my own role.",evidence:{Independence:78,Focus:74,Communication:38}}
  ]},
  {text:"You arrive at training feeling tired and unfocused. What are you most likely to do?",context:"Self-management",choices:[
    {text:"Tell the coach briefly, then set one realistic target for the session.",evidence:{"Self-Awareness":90,Communication:84,Accountability:86}},
    {text:"Follow my normal preparation routine and expect my energy to improve.",evidence:{Discipline:90,Resilience:78,Motivation:70}},
    {text:"Use the competitive activities to pull more energy out of myself.",evidence:{Competitiveness:88,Adaptability:74,Motivation:76}},
    {text:"Work quietly and avoid drawing attention to having an off day.",evidence:{Independence:76,Communication:38,"Self-Awareness":68}}
  ]},
  {text:"The coach gives the team freedom to solve a tactical problem with no immediate instruction. What role do you take?",context:"Independent problem-solving",choices:[
    {text:"Offer an idea and ask teammates what they are seeing.",evidence:{Leadership:88,Communication:90,Curiosity:84}},
    {text:"Experiment through play and adjust from the result.",evidence:{Adaptability:90,"Growth Mindset":82,Independence:82}},
    {text:"Observe a few repetitions before suggesting a pattern.",evidence:{Focus:90,"Decision Making":86,"Self-Awareness":70}},
    {text:"Work hard within my role and let more vocal players organize it.",evidence:{Discipline:82,Teamwork:72,Leadership:38}}
  ]}
];

function scoreAll(answers:Answers){
  const result = {} as Record<Dimension,number>; const totals={} as Record<Dimension,number>; const counts={} as Record<Dimension,number>;
  dimensions.forEach(d=>{totals[d]=0;counts[d]=0});
  questions.forEach((q,i)=>{const pick=answers[i+1]; if(!pick)return; const evidence=q.choices[pick-1]?.evidence||{}; Object.entries(evidence).forEach(([d,v])=>{totals[d as Dimension]+=v as number;counts[d as Dimension]++})});
  dimensions.forEach(d=>{result[d]=counts[d]?Math.round(totals[d]/counts[d]):50});
  return result;
}
function band(n:number){ return n>=75?"clear strength":n>=58?"emerging strength":n>=43?"situational":n>=28?"development area":"current challenge"; }
const behaviors: Record<Dimension,string> = {
  Coachability:"listen to feedback and test a coach’s correction",
  Confidence:"trust your ability and act without needing constant reassurance",
  Communication:"share useful information and ask for clarity when you need it",
  Leadership:"help organize, guide, or steady the players around you",
  Competitiveness:"raise your effort and look for ways to influence the result",
  "Emotional Control":"regain control of your reactions after frustration or disappointment",
  Resilience:"move forward after a mistake or difficult moment",
  Focus:"keep your attention on the next useful action",
  "Learning Style":"take in a new idea and turn it into action on the field",
  "Growth Mindset":"treat difficult skills as things that can improve with practice",
  "Decision Making":"notice your options and choose an action in time",
  Adaptability:"adjust when your role, position, or first plan changes",
  Teamwork:"make choices that help teammates and the team function together",
  "Self-Awareness":"notice what you are feeling, doing well, and needing to improve",
  Motivation:"find a reason to keep working even when the activity is difficult or repetitive",
  Discipline:"follow through on useful habits even when nobody is watching",
  Accountability:"recognize your part in an outcome and respond constructively",
  "Pressure Response":"stay usable and make purposeful choices when the moment feels important",
  Curiosity:"ask questions and look for the reason behind an instruction or situation",
  Independence:"solve problems and keep working without constant direction"
};
function sentence(label:Dimension,n:number){
  const action=behaviors[label];
  const openings={Coachability:"Feedback appears to become action quickly",Confidence:"Self-belief shows up through a willingness to act",Communication:"Useful information tends to be shared when it can help",Leadership:"Responsibility for others is a visible part of this profile",Competitiveness:"Competitive moments appear to raise involvement",Resilience:"Setbacks are usually followed by another attempt",Focus:"Attention is often directed toward the next useful cue","Learning Style":"New ideas appear to become clearer through active application","Growth Mindset":"Difficult skills are generally treated as learnable","Decision Making":"Options are often recognized in time to make a purposeful choice",Adaptability:"Changes in role or plan are usually met with an adjustment",Teamwork:"Choices regularly account for what teammates need","Self-Awareness":"Reflection is used to notice both strengths and next steps",Motivation:"Effort is supported by a meaningful target",Discipline:"Useful habits continue even without attention",Accountability:"Personal responsibility is usually recognized constructively","Pressure Response":"Important moments tend to invite purposeful involvement",Curiosity:"Understanding the reason behind an idea matters",Independence:"Problems are often approached with personal initiative","Emotional Control":"Emotions are usually redirected toward the next action"} as Record<Dimension,string>;
  if(n>=75) return `${openings[label]}, helping the player ${action}.`;
  if(n>=58) return `There is growing evidence of an ability to ${action}; it may become more visible with a clear role or familiar setting.`;
  if(n>=43) return `This part of the profile changes by situation. At times the player will ${action}, while other moments call out a different response.`;
  if(n>=28) return `A useful next step is practicing how to ${action} in one clear, repeatable situation.`;
  return `This assessment offers limited evidence here so far. A supportive starting point is learning to ${action} through small, low-pressure repetitions.`;
}
const developmentPlans: Record<Dimension,DevelopmentPlan> = {
  Coachability:{why:"Turning feedback into action helps a player improve during the session instead of waiting until later.",action:"After one correction, repeat the coach’s cue in your own words and test it for the next three repetitions.",progress:"The player needs fewer reminders and can explain which part of the correction helped."},
  Confidence:{why:"Decisive actions give teammates clearer information and allow skills to appear at game speed.",action:"Choose one action before training—call for the ball, attempt the forward pass, or take the shot when it is available—and commit to it three times.",progress:"Less hesitation in familiar moments and a quicker return to action after an imperfect attempt."},
  Communication:{why:"Early, specific information can solve pressure before it reaches a teammate.",action:"Use one short cue—“turn,” “time,” “man on,” or a teammate’s name—at least once in every small-sided round.",progress:"Messages arrive earlier, are more specific, and help a teammate make the next choice."},
  Leadership:{why:"Helpful leadership gives the group direction without requiring one player to control everything.",action:"Take ownership of one team task this week: organize a restart, check on a teammate, or lead the first response after losing possession.",progress:"Teammates receive useful direction and the player also listens to their response."},
  Competitiveness:{why:"Controlled competitive energy can raise intensity while protecting decision quality.",action:"Set a process challenge such as winning the next three transition reactions—not simply scoring or beating someone.",progress:"Effort rises after setbacks without rushed fouls, forced plays, or visible disengagement."},
  "Emotional Control":{why:"A quick emotional reset keeps one frustrating moment from affecting the next play.",action:"Use a three-part reset after frustration: one breath, one physical cue such as opening the hands, then locate the next job.",progress:"The player returns to position and useful decision-making within the next action or two."},
  Resilience:{why:"Mistakes become less costly when the player reconnects to the game immediately.",action:"After an error, say “next action,” scan once, and complete the simplest useful responsibility available.",progress:"Recovery is quicker and there is less chasing an immediate redemption play."},
  Focus:{why:"Consistent attention helps the player notice changes before the ball arrives.",action:"Pick one cue for each activity—scan, teammate, space, or transition—and name one example during the water break.",progress:"More early reactions and fewer reminders when the ball or phase of play changes."},
  "Learning Style":{why:"Knowing how an idea becomes clear makes coaching more efficient and less frustrating.",action:"For one new skill, use this sequence: watch one demonstration, hear one cue, then try it three times before adding more information.",progress:"The player can show the movement and explain the cue that made it click."},
  "Growth Mindset":{why:"Treating difficulty as information keeps a hard skill from becoming a judgment about ability.",action:"Choose one difficult skill and record one small change after each session: cleaner contact, better timing, or one extra successful repetition.",progress:"The player describes what is improving and requests another attempt instead of avoiding the task."},
  "Decision Making":{why:"Earlier information creates more time and makes both simple and creative options available.",action:"Before receiving, scan for three things: pressure, support, and forward space; afterward, name what was seen.",progress:"Choices happen earlier and the player can explain the option selected, even when execution is imperfect."},
  Adaptability:{why:"Games change quickly, and a player who can reset priorities remains useful in unfamiliar roles.",action:"When the role changes, ask for the two most important jobs and repeat them before play restarts.",progress:"The player settles into a new position faster and stays connected without constant sideline direction."},
  Teamwork:{why:"Individual quality has more impact when movements and choices give teammates usable options.",action:"After every pass in one activity, move immediately to create a new angle or open space for someone else.",progress:"The player is available more often and teammates receive clearer passing or covering options."},
  "Self-Awareness":{why:"Accurate reflection helps a player choose the right adjustment instead of relying on mood or outcome.",action:"After training, name one helpful action, one difficult moment, and one adjustment for next time.",progress:"Reflections become specific, balanced, and connected to observable moments."},
  Motivation:{why:"A personal reason for the work protects effort when practice becomes repetitive or difficult.",action:"Set one session target that the player controls, such as ten quality scans or five strong weak-foot passes.",progress:"Energy stays steadier and the player can evaluate effort without relying only on praise or results."},
  Discipline:{why:"Reliable habits turn good intentions into improvement that lasts across a season.",action:"Choose a five-minute routine to complete before or after three sessions this week and track each completion.",progress:"The routine happens without reminders and maintains quality even on low-energy days."},
  Accountability:{why:"Owning the controllable part of a moment makes the next solution easier to find.",action:"After one difficult play, finish the sentence: “My part was __; next time I will __.” Then release it.",progress:"Explanations include a specific personal adjustment without blame or excessive self-criticism."},
  "Pressure Response":{why:"A repeatable routine helps skill and judgment stay available when the moment feels important.",action:"Before a restart or high-pressure repetition, breathe out, scan one option, and use one cue word such as “simple” or “ready.”",progress:"Body language stays usable and the first decision under pressure becomes clearer."},
  Curiosity:{why:"Understanding why a tactic works helps the player transfer it to new game situations.",action:"Ask one purposeful question each week: what problem are we solving, what cue starts the movement, or what changes if pressure comes differently?",progress:"Questions become more specific and the player applies the answer in a later repetition."},
  Independence:{why:"Self-directed problem-solving helps development continue when the coach cannot provide every answer.",action:"During one activity, try a solution twice, observe the result, and make one adjustment before asking for help.",progress:"The player arrives with an idea, tests it, and can explain what changed."}
};
function planFor(label:Dimension){return developmentPlans[label]}
const archetypeVoices: Record<string,ArchetypeVoice> = {
  "The Field Captain":{role:"Steps into visible responsibility and helps give the group direction.",leadership:"Leads through clear instructions, teammate check-ins, and ownership of the group’s response.",pressure:"Often handles tension by becoming more active and giving the team something clear to follow.",mistakes:"Recovers best by owning the moment briefly, communicating the adjustment, and leading the next play.",focus:"Attention is strongest when there is a team problem to organize or a responsibility to carry.",parent:["Ask what responsibility the player took—not whether everyone followed.","Praise leadership that helps teammates think, rather than volume or control."]},
  "The Midfield Organizer":{role:"Connects players by noticing where the next pass, movement, or piece of information is needed.",leadership:"Leads tactically through positioning, passing options, and well-timed information.",pressure:"Often manages pressure by finding a workable option and keeping the team structure moving.",mistakes:"Recovers by identifying the missed option, then scanning earlier on the next play.",focus:"Attention centers on teammates, space, and how one action affects the next phase.",parent:["Ask what options the player noticed, including those not chosen.","Discuss what problem a safe or simple choice was solving."]},
  "The Team Connector":{role:"Supports teammates and adjusts to help the group function together.",leadership:"Leads relationally by encouraging, including, and filling gaps without demanding attention.",pressure:"Looks for a teammate or team action that can restore stability.",mistakes:"Recovers by reconnecting quickly with teammates instead of carrying the moment alone.",focus:"Sees the wider team picture, although personal details can be missed while helping others.",parent:["Ask how the player helped others and what the player needed too.","Recognize cooperation while encouraging personal ideas and needs."]},
  "The Goal Getter":{role:"Looks for a direct way to change the game and is energized by a visible challenge.",leadership:"Leads through initiative, demanding involvement, and raising the competitive level.",pressure:"May become more eager to act; urgency can make the boldest option feel better than the best one.",mistakes:"May try to make up for an error immediately; growth means keeping the ambition without forcing the next play.",focus:"Focus is strongest when there is a clear target, opponent, score, or outcome to chase.",parent:["Discuss decision quality, not only whether the ambitious play worked.","Set process targets alongside goals and statistics."]},
  "The Quiet Competitor":{role:"Contributes through personal standards, dependable work, and competition that needs little attention.",leadership:"Leads mostly by example through preparation, repetition, and reliability.",pressure:"Prefers to handle pressure internally and keep working rather than talk about it.",mistakes:"May recover quietly, so it helps to check whether the player reset or is still replaying the error.",focus:"Attention is helped by a personal task or standard the player can own.",parent:["Notice persistence without requiring the player to become louder.","Use calm, specific questions; silence does not always mean the moment is resolved."]},
  "The Calm Leader":{role:"Steadies the group and helps teammates see the next useful action.",leadership:"Leads selectively through calm information, emotional control, and dependable presence.",pressure:"Slows the moment mentally and gives the group stability rather than adding noise.",mistakes:"Resets calmly, while still needing to name and own the adjustment instead of only looking unaffected.",focus:"Returns attention to structure, the next task, and what the team can control.",parent:["Praise calm problem-solving, then ask what the player felt inside.","Do not assume a composed player needs no support."]},
  "The Tactical Thinker":{role:"Reads patterns and contributes through considered positioning and decisions.",leadership:"Leads with well-timed tactical observations rather than constant talking.",pressure:"Benefits from simple preplanned cues so limited time does not turn analysis into hesitation.",mistakes:"Learns through review, then needs one clear adjustment and permission to release the play.",focus:"Naturally tracks patterns, positioning, and cause-and-effect across the game.",parent:["Ask what pattern the player noticed and what one adjustment follows.","Put a time limit on postgame analysis so reflection does not become rumination."]},
  "The Relentless Learner":{role:"Seeks information, tests feedback, and helps make improvement normal within the group.",leadership:"Leads through curiosity, useful questions, and a willingness to accept correction.",pressure:"Benefits more from one familiar cue than from extra new information in a demanding moment.",mistakes:"Treats errors as learning material; progress means choosing one lesson rather than correcting everything at once.",focus:"Focus is strongest when the player understands the purpose and has one detail to test.",parent:["Ask what the player learned before asking how well they played.","Offer one observation at a time and leave room for the player’s conclusion."]},
  "The Creative Playmaker":{role:"Creates possibilities and attempts original solutions when the obvious option is closed.",leadership:"Leads through ideas and initiative rather than organizing the whole group.",pressure:"Pressure can unlock invention or rush it; the key is whether the creative choice fits the moment.",mistakes:"Separates the idea, timing, and execution before deciding whether to try the solution again.",focus:"Notices openings and possibilities, while routine team details may need a deliberate cue.",parent:["Ask what the player saw before judging an unsuccessful idea.","Balance freedom with one simple team responsibility to keep checking."]},
  "The Resilient Battler":{role:"Stays engaged through setbacks and gives the team competitive energy.",leadership:"Leads through effort, courage, and refusing to disappear after a difficult moment.",pressure:"Intensity rises under pressure; the goal is keeping that energy controlled enough for good choices.",mistakes:"Keeps fighting, but recovers best with a brief reset instead of chasing immediate redemption.",focus:"Can lock onto the contest or opponent; a tactical cue turns intensity into useful action.",parent:["Recognize the response after setbacks, not only toughness.","Help choose one reset action—breath, scan, or simple next pass."]},
  "The Composed Controller":{role:"Keeps decisions clear and helps the game feel manageable rather than chaotic.",leadership:"Leads through reliable choices and calm information that keeps teammates connected.",pressure:"Protects clarity, sees options, and avoids emotional rush when the moment becomes tense.",mistakes:"Recovers through a clean acknowledgment followed by the next simple action.",focus:"Stays with controllable information: ball, space, teammates, and the immediate decision.",parent:["Ask which choice helped the player regain control.","Discuss when control and risk were each appropriate."]},
  "The Adaptable Utility Player":{role:"Changes roles or methods without losing connection to the team.",leadership:"Leads through useful flexibility and by making transitions easier for others.",pressure:"Handles unexpected change best with one or two clear priorities for the new situation.",mistakes:"Recovers by adjusting to what the situation now requires rather than insisting on the original plan.",focus:"Responds to many cues, but a changing role needs a few anchor responsibilities.",parent:["Ask what changed and how the player adjusted.","Praise flexibility while helping identify the player’s strongest role."]},
  "The Independent Problem-Solver":{role:"Experiments and finds solutions without waiting for constant direction.",leadership:"Leads through initiative and useful solutions, even without being highly vocal.",pressure:"Self-trust helps action, but teammate information still matters before solving everything alone.",mistakes:"Uses the result as feedback and tests an adjustment instead of defending the first idea.",focus:"Concentrates best when given ownership of a real problem to solve.",parent:["Ask what the player tried, what happened, and what comes next.","Offer help before giving the solution so ownership remains with the player."]},
  "The Disciplined Builder":{role:"Contributes through repeatable habits, ownership, and patient improvement.",leadership:"Leads through reliability and standards rather than spotlight or emotion.",pressure:"Uses familiar routines to protect performance when the moment becomes unpredictable.",mistakes:"Returns to the process while naming the specific adjustment revealed by the error.",focus:"Works best with structure, measurable details, and a clear picture of a good repetition.",parent:["Recognize consistency, not only visible breakthroughs.","Leave room for experimentation so discipline does not become fear of change."]},
  "The Pressure Performer":{role:"Stays willing to act when the game reaches a demanding or visible moment.",leadership:"Leads through readiness, volunteering, and accepting responsibility.",pressure:"Important moments often increase involvement, especially when a clear routine is available.",mistakes:"Separates courage from outcome and reviews a failed high-pressure action without shame or revenge.",focus:"Importance sharpens attention; ordinary training may need a self-created challenge.",parent:["Praise willingness and preparation separately from the outcome.","Ask what routine the player wants to repeat next time."]}
};
function evidenceLead(score:number,strong:string,mixed:string,developing:string){return score>=68?strong:score>=48?mixed:developing;}
function voiceFor(type:ArchetypeMatch|null,scores:Record<Dimension,number>){
  const v=type?archetypeVoices[type.name]:null;
  return {role:v?.role??"The answers do not support one fixed team role; contribution may change by situation.",leadership:evidenceLead(scores.Leadership,v?.leadership??"Often organizes or supports others.",`Leadership appears situational. ${v?.leadership??"Some answers favor initiative and others favor contributing without directing."}`,`Leadership is not yet consistent. ${v?.leadership??"Small, clear responsibilities can build it."}`),pressure:evidenceLead(scores["Pressure Response"],v?.pressure??"Often stays purposeful under pressure.",`Pressure response was mixed. ${v?.pressure??"The reaction may depend on the moment."}`,`Pressure may currently change timing or choices. ${v?.pressure??"A short routine can be trained."}`),mistakes:evidenceLead(scores.Resilience,v?.mistakes??"Often returns to the next action.",`Mistake recovery appears situational. ${v?.mistakes??""}`,`Mistakes may stay with the player longer than useful. ${v?.mistakes??"Practice acknowledge, reset, refocus."}`),focus:evidenceLead(scores.Focus,v?.focus??"Often stays connected to the next action.",`Focus changes across situations. ${v?.focus??""}`,`Sustained focus is a development need. ${v?.focus??"Use one observable cue per activity."}`),parent:v?.parent??["Ask what the player noticed before evaluating.","Use the report as questions, not permanent labels."]};
}
function archetypes(scores:Record<Dimension,number>):ArchetypeMatch[]{
  const candidates = [
    {name:"The Field Captain", keys:["Leadership","Communication","Accountability"] as Dimension[],description:"Steps forward, gives useful direction, and accepts responsibility for the group."},
    {name:"The Midfield Organizer", keys:["Decision Making","Communication","Teamwork"] as Dimension[],description:"Connects teammates and looks for the choice that keeps the team functioning."},
    {name:"The Team Connector", keys:["Teamwork","Communication","Adaptability"] as Dimension[],description:"Helps different players work together and adjusts to what the team needs."},
    {name:"The Goal Getter", keys:["Competitiveness","Confidence","Motivation"] as Dimension[],description:"Is energized by challenges and looks for direct ways to influence the result."},
    {name:"The Quiet Competitor", keys:["Competitiveness","Independence","Discipline"] as Dimension[],description:"Competes through steady work and self-direction, even without much attention."},
    {name:"The Calm Leader", keys:["Leadership","Emotional Control","Pressure Response"] as Dimension[],description:"Can steady the moment and guide others without needing to be the loudest player."},
    {name:"The Tactical Thinker", keys:["Decision Making","Focus","Self-Awareness"] as Dimension[],description:"Studies what is happening, notices patterns, and thinks carefully about the next action."},
    {name:"The Relentless Learner", keys:["Coachability","Growth Mindset","Curiosity"] as Dimension[],description:"Looks for feedback, asks why, and treats difficult skills as learnable."},
    {name:"The Creative Playmaker", keys:["Confidence","Curiosity","Independence"] as Dimension[],description:"Explores possibilities and is willing to create a solution instead of waiting for one."},
    {name:"The Resilient Battler", keys:["Resilience","Competitiveness","Emotional Control"] as Dimension[],description:"Keeps competing through setbacks and works to regain control after difficult moments."},
    {name:"The Composed Controller", keys:["Emotional Control","Focus","Decision Making"] as Dimension[],description:"Tries to stay clear-headed, read the options, and keep the next action useful."},
    {name:"The Adaptable Utility Player", keys:["Adaptability","Coachability","Teamwork"] as Dimension[],description:"Can take instruction, change roles, and contribute where the team needs help."},
    {name:"The Independent Problem-Solver", keys:["Independence","Decision Making","Curiosity"] as Dimension[],description:"Likes to read the problem, test ideas, and find a solution without constant direction."},
    {name:"The Disciplined Builder", keys:["Discipline","Accountability","Growth Mindset"] as Dimension[],description:"Improves through dependable habits, ownership, and patient work over time."},
    {name:"The Pressure Performer", keys:["Pressure Response","Confidence","Focus"] as Dimension[],description:"Appears ready to stay involved and act purposefully when the moment feels important."},
  ];
  const profileAverage=dimensions.reduce((sum,key)=>sum+scores[key],0)/dimensions.length;
  const rawMatches=candidates.map((c,avatar)=>{
    const evidenceAverage=c.keys.reduce((sum,key)=>sum+scores[key],0)/c.keys.length;
    const distinctiveness=evidenceAverage-profileAverage;
    // Distinctive evidence matters more than a generally high-scoring response style.
    const rawMatch=Math.max(0,Math.min(100,evidenceAverage+distinctiveness*.9));
    return {...c,avatar,rawMatch};
  }).sort((a,b)=>b.rawMatch-a.rawMatch);
  const leader=rawMatches[0]?.rawMatch||1;
  return rawMatches.map((candidate,index)=>{
    // Keep the leader's evidence score, then calibrate secondary patterns against it.
    // This prevents several broadly positive traits from making every archetype look dominant.
    const relative=index===0?candidate.rawMatch:candidate.rawMatch*Math.pow(candidate.rawMatch/leader,4);
    const {rawMatch,...archetype}=candidate;
    return {...archetype,match:Math.max(0,Math.min(100,Math.round(relative)))};
  });
}

function Radar({scores}:{scores:Record<Dimension,number>}){
  const keys = reportDimensions.slice(0,6), center=110, radius=76;
  const point=(i:number,r:number)=>{const a=-Math.PI/2+i*Math.PI*2/keys.length;return `${center+Math.cos(a)*r},${center+Math.sin(a)*r}`};
  return <svg className="radar" viewBox="0 0 220 220" role="img" aria-label="Player score radar chart">
    {[.25,.5,.75,1].map(r=><polygon key={r} points={keys.map((_,i)=>point(i,radius*r)).join(" ")} className="radar-grid" />)}
    {keys.map((_,i)=><line key={i} x1={center} y1={center} x2={point(i,radius).split(",")[0]} y2={point(i,radius).split(",")[1]} className="radar-line" />)}
    <polygon points={keys.map((k,i)=>point(i,radius*scores[k]/100)).join(" ")} className="radar-shape" />
    {keys.map((k,i)=>{const [x,y]=point(i,98).split(",");return <text key={k} x={x} y={y} textAnchor="middle" dominantBaseline="middle">{k==='Growth Mindset'?'Growth':k}</text>})}
  </svg>
}

export default function Home(){
  const [step,setStep]=useState<"intro"|"form"|"report">("intro"); const [answers,setAnswers]=useState<Answers>({});
  const [info,setInfo]=useState<{name:string;email:string;age:string;position:string;notes:string;gender:PlayerGender|"";consent:boolean}>({name:"",email:"",age:"",position:"",notes:"",gender:"",consent:false}); const [current,setCurrent]=useState(0); const [sending,setSending]=useState(false); const [sent,setSent]=useState("");
  const scores=useMemo(()=>scoreAll(answers),[answers]); const matches=useMemo(()=>archetypes(scores),[scores]); const type=matches[0]?.match>=58?matches[0]:null; const closeMatches=type?matches.slice(0,4):matches.slice(0,3);
  const voice=useMemo(()=>voiceFor(type,scores),[type,scores]);
  const strengths=[...dimensions].sort((a,b)=>scores[b]-scores[a]).slice(0,3); const priorities=[...dimensions].sort((a,b)=>scores[a]-scores[b]).slice(0,5);
  const answered=Object.keys(answers).length; const date=new Intl.DateTimeFormat("en-US",{year:"numeric",month:"long",day:"numeric"}).format(new Date());
  const strengthStory=strengths.map(s=>sentence(s,scores[s])).join(' ');
  const profileSummary=type?`${info.name}’s clearest pattern is ${type.name}. ${voice.role} The strongest supporting themes are ${strengths.map(s=>s.toLowerCase()).join(', ')}. ${strengthStory} Together, these answers suggest a player who can contribute in more than one way; the archetype names the leading pattern, not a fixed identity.`:`${info.name}’s answers do not point to one dominant archetype, which can be useful evidence in itself. The clearest themes are ${strengths.map(s=>s.toLowerCase()).join(', ')}. ${strengthStory} This profile is best used to explore which environments bring each quality forward.`;
  const reportContent={summary:profileSummary,learning:`${sentence('Learning Style',scores['Learning Style'])} ${scores['Learning Style']>=58?'Seeing the movement and trying it soon afterward may help. Demonstrate one skill, offer one cue, and allow a few attempts before adding information.':'No single learning route dominates these answers. Combine a short explanation, a demonstration, and a chance to experiment, then ask what made the idea clearer.'}`,communication:`${sentence('Communication',scores.Communication)} Invite the player to ask one question or restate the instruction; that gives better evidence of understanding than silence alone.`,pressure:voice.pressure,mistakes:voice.mistakes,focus:voice.focus,role:voice.role,leadership:voice.leadership,teamwork:`${sentence('Teamwork',scores.Teamwork)} ${sentence('Adaptability',scores.Adaptability)}`,parent:voice.parent,priorities:priorities.map(k=>({name:k,...planFor(k),text:`Why it matters: ${planFor(k).why}\nTry this: ${planFor(k).action}\nProgress may look like: ${planFor(k).progress}`}))};
  async function submit(){ if(!info.name||!info.email||answered<20)return; setSending(true); setStep("report"); window.scrollTo({top:0,behavior:"smooth"});
    try{const pdfBase64=await buildPdf(false);const res=await fetch('/api/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player:info,answers,questions:questions.map(q=>q.text),scores,archetype:type?.name??null,archetypeMatches:matches.slice(0,4).map(m=>({name:m.name,match:m.match,description:m.description})),report:reportContent,pdfBase64,completedAt:new Date().toISOString()})}); const data=await res.json(); setSent(data.emailSent?"Your report was emailed successfully, and Coach Al was notified.":"Your report is ready to download. Email delivery needs attention.");}catch{setSent("Your report is ready to download.");}finally{setSending(false)} }
  async function buildPdf(saveFile=true):Promise<string|void>{
    const {jsPDF}=await import('jspdf'); const doc=new jsPDF({unit:'pt',format:'letter'});
    const navy=[10,35,66] as [number,number,number],blue=[17,91,168] as [number,number,number],sky=[108,174,237] as [number,number,number],ink=[22,39,59] as [number,number,number],muted=[92,110,132] as [number,number,number];
    const margin=48,width=516; let y=0,sectionNo=0;
    const avatar=await new Promise<string|null>(resolve=>{if(!type)return resolve(null);const img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=360;canvas.height=360;const ctx=canvas.getContext('2d');if(!ctx)return resolve(null);const sw=img.naturalWidth/5,sh=img.naturalHeight/3;ctx.drawImage(img,(type.avatar%5)*sw,Math.floor(type.avatar/5)*sh,sw,sh,0,0,360,360);resolve(canvas.toDataURL('image/png'))};img.onerror=()=>resolve(null);img.src=info.gender==='girl'?'/archetype-avatar-sheet-girl-v2.webp':'/archetype-avatar-sheet-boy-v3.webp'});
    const footer=()=>{doc.setDrawColor(217,227,237);doc.line(margin,752,612-margin,752);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.setTextColor(...muted);doc.text('CASTRO PLAYER DEVELOPMENT',margin,770);doc.setFont('helvetica','normal');doc.text(`PRIVATE PLAYER PROFILE  ·  ${doc.getNumberOfPages()}`,612-margin,770,{align:'right'})};
    const page=(label?:string)=>{if(doc.getNumberOfPages()>1||y>0)footer();doc.addPage();doc.setFillColor(247,250,253);doc.rect(0,0,612,792,'F');doc.setFillColor(...navy);doc.rect(0,0,612,12,'F');doc.setFont('helvetica','bold');doc.setFontSize(8);doc.setTextColor(...blue);doc.text(label||'PLAYER DEVELOPMENT PROFILE',margin,42);y=70};
    const heading=(title:string,eyebrow?:string)=>{if(y>686)page(eyebrow);sectionNo++;doc.setFont('helvetica','bold');doc.setFontSize(8);doc.setTextColor(...blue);doc.text(`${String(sectionNo).padStart(2,'0')}  ·  ${(eyebrow||'PLAYER INSIGHT').toUpperCase()}`,margin,y);y+=24;doc.setFontSize(22);doc.setTextColor(...ink);doc.text(title,margin,y);y+=30};
    const paragraph=(text:string,opts?:{indent?:number;size?:number;gap?:number})=>{const x=margin+(opts?.indent||0),w=width-(opts?.indent||0);doc.setFont('helvetica','normal');doc.setFontSize(opts?.size||10);doc.setTextColor(...muted);const lines=doc.splitTextToSize(text,w);if(y+lines.length*14>730)page();doc.text(lines,x,y,{lineHeightFactor:1.42});y+=lines.length*14+(opts?.gap??14)};
    const card=(title:string,text:string)=>{const lines=doc.splitTextToSize(text,width-40);const h=48+lines.length*13;if(y+h>730)page();doc.setFillColor(255,255,255);doc.setDrawColor(220,229,238);doc.roundedRect(margin,y,width,h,5,5,'FD');doc.setFillColor(...blue);doc.rect(margin,y,5,h,'F');doc.setFont('helvetica','bold');doc.setFontSize(11);doc.setTextColor(...ink);doc.text(title,margin+20,y+23);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(...muted);doc.text(lines,margin+20,y+42,{lineHeightFactor:1.42});y+=h+12};
    const miniTitle=(title:string)=>{if(y>700)page();doc.setFont('helvetica','bold');doc.setFontSize(11);doc.setTextColor(...ink);doc.text(title,margin,y);y+=18};
    doc.setFillColor(...navy);doc.rect(0,0,612,792,'F');doc.setDrawColor(44,94,145);doc.circle(510,145,150,'S');doc.circle(510,145,112,'S');doc.setFillColor(...blue);doc.circle(504,126,82,'F');if(avatar){doc.setFillColor(255,255,255);doc.circle(504,126,66,'F');doc.addImage(avatar,'PNG',444,66,120,120)}doc.setTextColor(...sky);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('CASTRO PLAYER DEVELOPMENT  ·  CONFIDENTIAL',54,74);doc.setTextColor(255,255,255);doc.setFontSize(34);doc.text(info.name,54,228,{maxWidth:330});doc.setFontSize(19);doc.setFont('helvetica','normal');doc.setTextColor(199,216,234);doc.text('PLAYER DEVELOPMENT PROFILE',54,270);doc.setDrawColor(...sky);doc.line(54,300,280,300);doc.setFontSize(10);doc.text(`${date}  ·  ${info.position||'Player'}  ·  Assessment 01`,54,326);doc.setFillColor(8,28,53);doc.roundedRect(54,390,300,132,8,8,'F');doc.setFont('helvetica','bold');doc.setFontSize(8);doc.setTextColor(...sky);doc.text('LEADING ARCHETYPE',76,419);doc.setFontSize(24);doc.setTextColor(255,255,255);doc.text(type?.name??'Developing Profile',76,458,{maxWidth:245});if(type){doc.setFontSize(12);doc.setTextColor(...sky);doc.text(`${type.match}% relative match`,76,497)}doc.setFont('helvetica','normal');doc.setFontSize(10);doc.setTextColor(181,203,226);doc.text('Evidence-based. Development-focused. Never a label.',54,712);
    page('EXECUTIVE SUMMARY');heading(type?`${type.name}, in this player’s own way.`:'A versatile profile still taking shape.','Executive summary');paragraph(profileSummary,{size:11,gap:20});doc.setFillColor(231,241,251);doc.roundedRect(margin,y,width,62,5,5,'F');doc.setFont('helvetica','bold');doc.setFontSize(9);doc.setTextColor(...blue);doc.text('HOW TO READ THIS',margin+18,y+21);doc.setFont('helvetica','normal');doc.setTextColor(...muted);doc.text(doc.splitTextToSize('This profile describes this set of answers. It is a coaching conversation starter—not a diagnosis, prediction, or permanent identity.',width-36),margin+18,y+39,{lineHeightFactor:1.35});y+=86;
    heading('One leading pattern, with other sides nearby.','Archetype mix');paragraph('The leading pattern keeps its evidence score. Nearby patterns are calibrated against that leader so broadly positive answers do not make every archetype appear equally dominant.',{size:9,gap:13});closeMatches.forEach((match,index)=>{if(y+76>730)page();doc.setFillColor(255,255,255);doc.setDrawColor(220,229,238);doc.roundedRect(margin,y,width,66,4,4,'FD');doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(...ink);doc.text(`${index===0?'LEADING MATCH':'ALSO PRESENT'}  ·  ${match.name}`,margin+16,y+20);doc.setTextColor(...blue);doc.text(`${match.match}%`,margin+width-16,y+20,{align:'right'});doc.setFillColor(225,233,241);doc.roundedRect(margin+16,y+30,width-32,6,3,3,'F');doc.setFillColor(...sky);doc.roundedRect(margin+16,y+30,(width-32)*match.match/100,6,3,3,'F');doc.setFont('helvetica','normal');doc.setFontSize(8.5);doc.setTextColor(...muted);doc.text(doc.splitTextToSize(match.description,width-32),margin+16,y+51);y+=76});
    page('HOW THE PLAYER MAY OPERATE');heading('Learning & communication','Player approach');card('LEARNING',reportContent.learning);card('COMMUNICATION',reportContent.communication);heading('Pressure, mistakes & focus','Mental game');card('UNDER PRESSURE',voice.pressure);card('AFTER A MISTAKE',voice.mistakes);card('STAYING FOCUSED',voice.focus);
    page('THE PLAYER WITH OTHERS');heading('Role, leadership & collaboration','Team dynamics');card('LIKELY ROLE',voice.role);card('LEADERSHIP',voice.leadership);card('TEAMWORK & ADAPTABILITY',reportContent.teamwork);heading('Support at home','Parent guide');voice.parent.forEach(item=>card('CONVERSATION IDEA',item));card('KEEP IT FLEXIBLE','Use the archetype as a conversation starter, not a permanent description. Ask: “When did this part of your profile show up today—and when did you respond differently?”');
    page('ACTION PLAN');heading('Five specific opportunities to train next','Development priorities');priorities.forEach((k,i)=>{const plan=planFor(k);if(y+168>730)page('ACTION PLAN');doc.setFillColor(...blue);doc.circle(margin+18,y+18,18,'F');doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(255,255,255);doc.text(String(i+1).padStart(2,'0'),margin+18,y+22,{align:'center'});doc.setFontSize(16);doc.setTextColor(...ink);doc.text(k,margin+48,y+23);y+=48;miniTitle('Why it matters');paragraph(plan.why,{indent:14,size:9,gap:8});miniTitle('Try this');paragraph(plan.action,{indent:14,size:9,gap:8});miniTitle('Progress may look like');paragraph(plan.progress,{indent:14,size:9,gap:18});doc.setDrawColor(222,230,238);doc.line(margin,y-7,margin+width,y-7)});
    page('CLOSING NOTE');doc.setFillColor(...navy);doc.roundedRect(margin,86,width,300,10,10,'F');doc.setFont('helvetica','bold');doc.setFontSize(9);doc.setTextColor(...sky);doc.text('USE THE PROFILE. KEEP WATCHING THE PLAYER.',margin+30,124);doc.setFontSize(25);doc.setTextColor(255,255,255);doc.text('Insight becomes useful\nwhen it changes the\nnext conversation.',margin+30,174,{lineHeightFactor:1.2});doc.setFont('helvetica','normal');doc.setFontSize(10);doc.setTextColor(196,214,232);doc.text(doc.splitTextToSize(`This assessment gives ${info.name}, family and coaches a shared starting point. Test these ideas in training, notice what changes, and reassess with fresh evidence over time.`,width-60),margin+30,294,{lineHeightFactor:1.5});if(avatar)doc.addImage(avatar,'PNG',422,420,120,120);doc.setFont('helvetica','bold');doc.setFontSize(18);doc.setTextColor(...ink);doc.text(type?.name??'Developing Profile',margin,474);doc.setFont('helvetica','normal');doc.setFontSize(10);doc.setTextColor(...muted);doc.text('Better insight. Better coaching. Better growth.',margin,500);footer();if(saveFile){doc.save(`${info.name.replace(/[^a-z0-9]/gi,'-').toLowerCase()}-player-profile.pdf`);return}return doc.output('datauristring').split(',')[1];
  }

  return <main>
    <header className="topbar"><a className="brand" href="#" onClick={()=>setStep('intro')}><span className="mark">CPD</span><span>CASTRO <b>PLAYER DEVELOPMENT</b></span></a><span className="method">EVIDENCE-BASED PLAYER INSIGHT</span></header>
    {step==='intro'&&<section className="hero"><div className="pitch-lines"/><div className="hero-copy"><p className="eyebrow">PLAYER DEVELOPMENT PROFILE · 20 SCENARIOS</p><h1>Understand the player.<br/><em>Develop the person.</em></h1><p className="lede">Choose what you would most likely do in realistic soccer situations. Every option reflects a different approach—there are no perfect answers.</p><button className="primary" onClick={()=>setStep('form')}>Begin assessment <span>→</span></button><p className="quiet">About 8 minutes · Private · Development-focused</p></div><aside className="profile-card"><div className="card-top"><span>WHAT YOU’LL DISCOVER</span><b>01 / 04</b></div><div className="mini-field"><div className="field-circle"/><span className="player-dot p1"/><span className="player-dot p2"/><span className="player-dot p3"/></div><h2>A clearer coaching picture</h2><p>Communication, learning, pressure response, teamwork and the next priorities to train.</p><div className="chips"><span>PDF REPORT</span><span>COACH ACTIONS</span><span>PARENT GUIDE</span></div></aside></section>}
    {step==='form'&&<section className="assessment"><div className="form-head"><div><p className="eyebrow">PLAYER ASSESSMENT</p><h1>{current===0?'First, tell us about the player.':`Question ${current} of 20`}</h1></div><div className="progress-meta"><span>{Math.round((current/20)*100)}%</span><div><i style={{width:`${current/20*100}%`}}/></div></div></div>
      {current===0?<div className="info-grid"><label>Player name<input value={info.name} onChange={e=>setInfo({...info,name:e.target.value})} placeholder="Full name"/></label><label>Parent / player email<input type="email" value={info.email} onChange={e=>setInfo({...info,email:e.target.value})} placeholder="name@email.com"/></label><label>Age <input value={info.age} onChange={e=>setInfo({...info,age:e.target.value})} placeholder="e.g. 12"/></label><label>Primary position<input value={info.position} onChange={e=>setInfo({...info,position:e.target.value})} placeholder="e.g. Center midfielder"/></label><fieldset className="character-choice wide"><legend>Gender</legend><p>This only selects the matching superhero artwork. It never changes the player’s scores or archetype.</p><div><button type="button" className={info.gender==='boy'?'selected':''} onClick={()=>setInfo({...info,gender:'boy'})}>Boy</button><button type="button" className={info.gender==='girl'?'selected':''} onClick={()=>setInfo({...info,gender:'girl'})}>Girl</button></div></fieldset><label className="wide">Coach notes <span>(optional)</span><textarea value={info.notes} onChange={e=>setInfo({...info,notes:e.target.value})} placeholder="Context for this assessment or future reassessment"/></label><label className="wide consent"><input type="checkbox" checked={info.consent} onChange={e=>setInfo({...info,consent:e.target.checked})}/><span>I am the player or the player’s parent/guardian, and I consent to these responses being stored privately and emailed for development purposes.</span></label></div>:<div className="question-card scenario-card"><p className="dimension">{questions[current-1].context.toUpperCase()} · CHOOSE THE CLOSEST MATCH</p><h2>{questions[current-1].text}</h2><div className="scale scenario-options">{questions[current-1].choices.map((choice,i)=><button key={choice.text} className={answers[current]===i+1?'selected':''} onClick={()=>setAnswers({...answers,[current]:i+1})}><b>{String.fromCharCode(65+i)}</b><span>{choice.text}</span></button>)}</div><p className="hint">Choose what you would most likely do—not what sounds most impressive. Each option has useful qualities and tradeoffs.</p></div>}
      <div className="form-actions"><button className="back" disabled={current===0} onClick={()=>setCurrent(Math.max(0,current-1))}>← Back</button>{current<20?<button className="primary" disabled={(current===0&&(!info.name||!info.email||!info.gender||!info.consent))||(current>0&&!answers[current])} onClick={()=>setCurrent(current+1)}>Continue →</button>:<button className="primary" disabled={!answers[20]||sending} onClick={submit}>{sending?'Building profile…':'Generate my profile →'}</button>}</div>
    </section>}
    {step==='report'&&<section className="report"><div className="report-hero"><div><p className="eyebrow">CASTRO PLAYER DEVELOPMENT · CONFIDENTIAL</p><h1>{info.name}</h1><p>Player Development Profile</p><div className="report-meta"><span>{date}</span><span>{info.position||'Player'}</span><span>Assessment 01</span></div></div><div className="archetype-feature">{type&&<div className={`archetype-avatar ${info.gender==='girl'?'girl':''}`} role="img" aria-label={`${type.name} ${info.gender} superhero avatar`} style={{"--avatar-col":type.avatar%5,"--avatar-row":Math.floor(type.avatar/5)} as CSSProperties}/>}<div className="score-seal archetype-seal"><span>LEADING ARCHETYPE</span><b>{type?.name??'Developing Profile'}</b>{type&&<strong>{type.match}% match</strong>}</div></div></div>
      <div className="report-toolbar"><p>{sent||'Building your delivery confirmation…'}</p><button onClick={()=>buildPdf(true)}>Download PDF ↓</button></div>
      <div className="report-grid"><article className="paper summary"><p className="section-no">01 · EXECUTIVE SUMMARY</p><h2>{type?`${type.name}, in this player’s own way.`:'A versatile profile still taking shape.'}</h2><p>{profileSummary}</p><div className="evidence-note">Interpretation rule: scores describe this set of answers on this date. They are not diagnoses, predictions, or permanent traits.</div></article><article className="paper radar-wrap"><p className="section-no">02 · PROFILE SHAPE</p><Radar scores={scores}/><p>Higher points indicate stronger support in the response pattern—not greater worth or potential.</p></article></div>
      <article className="paper archetype-spectrum"><p className="section-no">03 · ARCHETYPE MIX</p><h2>One leading pattern, with other sides nearby.</h2><p className="spectrum-intro">These are calibrated relative matches—not probabilities or permanent personality scores. The leading pattern keeps its evidence score; nearby patterns are measured against that leader so broadly positive answers do not make every archetype look equally dominant.</p><div className="match-list">{closeMatches.map((match,index)=><div className="match-row" key={match.name}><div className={`archetype-avatar small ${info.gender==='girl'?'girl':''}`} role="img" aria-label={`${match.name} ${info.gender} superhero avatar`} style={{"--avatar-col":match.avatar%5,"--avatar-row":Math.floor(match.avatar/5)} as CSSProperties}/><div className="match-copy"><div><h3>{index===0&&type?'Leading match':index===0?'Closest pattern':'Also present'} · {match.name}</h3><b>{match.match}%</b></div><i><em style={{width:`${match.match}%`}}/></i><p>{match.description}</p></div></div>)}</div></article>
      <article className="paper scores"><div><p className="section-no">04 · CORE INDICATORS</p><h2>What the answers support</h2></div><div className="bars">{reportDimensions.map(k=><div className="bar" key={k}><div><span>{k}</span><small>{band(scores[k])}</small><b>{scores[k]}</b></div><i><em style={{width:`${scores[k]}%`}}/></i></div>)}</div></article>
      <div className="report-grid"><article className="paper"><p className="section-no">04 · LEARNING & COMMUNICATION</p><h2>How this player may learn best</h2><p>{sentence('Learning Style',scores['Learning Style'])} {scores['Learning Style']>=58?'The answers indicate that seeing the movement and then trying it shortly afterward may help. A coach can demonstrate one skill, give one clear instruction—such as “open your hips before receiving”—and let the player repeat it immediately.':'The answers do not point clearly to only one way of learning. A coach should combine a short explanation, a visual demonstration, and a chance to try the skill, then ask the player which part made the idea click.'}</p><h3>Communication style</h3><p>{sentence('Communication',scores.Communication)} In practice, give the player space to ask a question or repeat the instruction in their own words; this confirms understanding more clearly than silence does.</p></article><article className="paper"><p className="section-no">05 · MENTAL GAME</p><h2>Pressure, mistakes & focus</h2><h3>Under pressure</h3><p>{voice.pressure}</p><h3>After a mistake</h3><p>{voice.mistakes}</p><h3>Staying focused</h3><p>{voice.focus}</p><h3>Competitive mindset</h3><p>{sentence('Competitiveness',scores.Competitiveness)} Competitive energy may look like extra effort, taking responsibility, or wanting a difficult challenge; it does not have to look loud or emotional.</p></article></div>
      <div className="report-grid"><article className="paper"><p className="section-no">06 · TEAM DYNAMICS</p><h2>Role, leadership & collaboration</h2><h3>Likely role in the group</h3><p>{voice.role}</p><h3>How leadership may appear</h3><p>{voice.leadership}</p><h3>Working with teammates</h3><p>{sentence('Teamwork',scores.Teamwork)} {sentence('Adaptability',scores.Adaptability)}</p><h3>For the coach</h3><ul><li>Give one observable behavior to try, then ask what the player noticed.</li><li>Use short feedback loops: cue, repetition, player reflection.</li><li>Match responsibility to current evidence and reassess after real game situations.</li></ul></article><article className="paper"><p className="section-no">07 · SUPPORT AT HOME</p><h2>For the parent of {type?.name.replace('The ','a ')??'this player'}</h2><ul>{voice.parent.map(item=><li key={item}>{item}</li>)}<li>Use the archetype as a conversation starter, not a permanent description.</li></ul><p className="parent-note">Helpful prompt: “When did this part of your profile show up today—and when did you respond differently?”</p></article></div>
      <article className="paper priorities"><p className="section-no">08 · DEVELOPMENT PRIORITIES</p><h2>Five specific opportunities to train next</h2><div className="priority-grid">{priorities.map((k,i)=>{const plan=planFor(k);return <div key={k}><span>0{i+1}</span><h3>{k}</h3><p><b>Why it matters</b>{plan.why}</p><p><b>Try this</b>{plan.action}</p><p><b>Progress may look like</b>{plan.progress}</p></div>})}</div></article>
      <article className="closing"><span className="mark">CPD</span><div><p className="section-no">CLOSING NOTE</p><h2>Use the profile. Keep watching the player.</h2><p>This assessment gives {info.name}, family and coaches a shared starting point. The most useful next step is not to protect the scores—it is to test the ideas in training, notice what changes, and reassess with fresh evidence over time.</p></div></article>
    </section>}
    <footer><span>CASTRO PLAYER DEVELOPMENT</span><span>Better insight. Better coaching. Better growth.</span></footer>
  </main>
}
